#!/bin/bash
# determines this name of this host by comparing config/ips with ifconfig

source setup_env.sh

if [ $(uname) == "Darwin" ]; then
    # macOS
    echo $(ifconfig en0 |
        grep "inet " |
        awk '{print $2}')
else
    echo $(ifconfig eth0 |
        grep "inet addr" |
        sed "s/^[^:]*://" |
        sed "s/ .*//")
fi
