#!/usr/bin/env python
from os import getenv
from random import random as r

for i in xrange(100):
    # 50% chance of 'INS' vs. 'REM'
    tx_type = (r() > 0.5) and 'INS' or 'REM'
    amount = int(r() * 100)
    print tx_type, amount
