#!/usr/bin/env python
from os import getenv
from random import random as random_float

random_int = lambda max_num: int(random_float() * max_num)

r = lambda: random_int(100)

for i in range(100):
    # 60% chance of 'GET' vs. 'PUT'
    transaction_type = (random_float() < 0.6) and 'GET' or 'PUT'
    if transaction_type == 'GET':
        args = [r()]
    else:
        args = [r(), r()]
    # random integers for both
    print(transaction_type, *args)
